[package]
name = "rust_stager"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
kernel32-sys = "0.2.2"
mmap = "0.1.1"
reqwest = { version = "0.11.18", features = ["blocking", "native-tls"]}
winapi = { version = "0.3.9", features = ["memoryapi", "processthreadsapi", "synchapi","errhandlingapi"]}
